# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160629_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userdetails',
            new_name='Userdetail',
        ),
    ]
